---
platform: linux

image_resource:
  type: docker-image
  source: { repository: maven, tag: 3.5.0-jdk-8-alpine }

inputs:
  - name: demo-src

outputs:
  - name: build

caches:
  - path: demo-src/.m2

run:
  path: demo-src/build.sh