---
resources:
  - name: demo-src
    type: git
    source:
      uri: https://github.com/Turbots/concourse-spring-boot-app.git
      branch: master
  - name: cf-experimental
    type: cf
    source:
      api: https://api.run.pivotal.io
      username: dieter.hubau@ordina.be
      password: ((CF_PASSWORD))
      organization: OrdinaBelgiumNV
      space: experimental
      skip_cert_check: false
jobs:
  - name: build-demo-app
    build_logs_to_retain: 30
    plan:
      - aggregate:
          - get: demo-src
            trigger: true
      - task: build
        file: demo-src/build.yml
      - put: cf-experimental

groups:
  - name: demo-app
    jobs:
      - build-demo-app