---
platform: linux

image_resource:
  type: docker-image
  source: { repository: maven, tag: 3.5.0-jdk-8-alpine }

inputs:
  - name: source

outputs:
  - name: build

caches:
  - path: source/.m2

run:
  path: source/ci/build.sh