---
resource_types:
  - name: maven-resource
    type: docker-image
    source:
      repository: nulldriver/maven-resource
      tag: latest
resources:
  - name: source
    type: git
    source:
      uri: https://github.com/Turbots/concourse-spring-boot-app.git
      branch: master
  - name: artifact
    type: maven-resource
    source:
      url: http://nexus:8081/repository/maven-releases/
      snapshot_url: http://nexus:8081/repository/maven-snapshots/
      artifact: be.turbots:concourse-pipeline-demo:jar
      username: ((NEXUS_USER))
      password: ((NEXUS_PASSWORD))
  - name: cf-dev
    type: cf
    source:
      api: https://api.run.pivotal.io
      username: dieter.hubau@ordina.be
      password: ((CF_PASSWORD))
      organization: OrdinaBelgiumNV
      space: development
      skip_cert_check: false
  - name: cf-prod
    type: cf
    source:
      api: https://api.run.pivotal.io
      username: dieter.hubau@ordina.be
      password: ((CF_PASSWORD))
      organization: OrdinaBelgiumNV
      space: production
      skip_cert_check: false
jobs:
  - name: build
    build_logs_to_retain: 30
    plan:
      - get: source
        trigger: true
      - task: build
        file: source/ci/build.yml
      - put: artifact
        params:
          file: build/*.jar
          pom_file: source/pom.xml
  - name: deploy-to-dev
    build_logs_to_retain: 30
    plan:
      - get: source
        passed: [build]
        trigger: true
      - get: artifact
      - put: cf-dev
        params:
          manifest: source/ci/manifest-dev.yml
          path: artifact/concourse-pipeline-demo-*.jar
  - name: integration-test
    build_logs_to_retain: 5
    plan:
      - get: source
        passed: [deploy-to-dev]
        trigger: true
      - task: integration-test
        file: source/ci/integration-test.yml
  - name: deploy-to-prod
    build_logs_to_retain: 30
    plan:
      - get: source
        passed: [integration-test]
        trigger: true
      - get: artifact
      - put: cf-prod
        params:
          manifest: source/ci/manifest-prod.yml
          path: artifact/concourse-pipeline-demo-*.jar

groups:
  - name: demo-app
    jobs:
      - build
      - deploy-to-dev
      - integration-test
      - deploy-to-prod