---
resource_types:
  - name: maven-resource
    type: docker-image
    source:
      repository: nulldriver/maven-resource
      tag: latest
resources:
  - name: demo-src
    type: git
    source:
      uri: https://github.com/Turbots/concourse-spring-boot-app.git
      branch: master
  - name: artifact
    type: maven-resource
    source:
      url: http://nexus:8081/repository/maven-releases/
      artifact: "be.turbots:concourse-pipeline-demo"
      username: ((NEXUS_USER))
      password: ((NEXUS_PASSWORD))
  - name: cf-dev
    type: cf
    source:
      api: https://api.run.pivotal.io
      username: dieter.hubau@ordina.be
      password: ((CF_PASSWORD))
      organization: OrdinaBelgiumNV
      space: development
      skip_cert_check: false
  - name: cf-prod
    type: cf
    source:
      api: https://api.run.pivotal.io
      username: dieter.hubau@ordina.be
      password: ((CF_PASSWORD))
      organization: OrdinaBelgiumNV
      space: production
      skip_cert_check: false
jobs:
  - name: build
    build_logs_to_retain: 30
    plan:
      - get: demo-src
        trigger: true
      - task: build
        file: demo-src/ci/build.yml
      - put: artifact
        params:
          file: build/demo-app.jar
          pom_file: demo-src/pom.xml
  - name: deploy-to-dev
    build_logs_to_retain: 30
    plan:
      - get: demo-src
        passed: [build]
      - get: artifact
        trigger: true
      - put: cf-dev
        params:
          manifest: demo-src/ci/manifest.yml
          path: artifact/demo-app.jar
  - name: integration-test
    build_logs_to_retain: 5
    plan:
      - aggregate:
        - get: demo-src
          passed: [deploy-to-dev]
      - task: integration-test
        file: demo-src/ci/integration-test.yml
  - name: deploy-to-prod
    build_logs_to_retain: 30
    plan:
      - get: demo-src
        passed: [integration-test]
      - get: artifact
        trigger: true
      - put: cf-prod
        params:
          manifest: demo-src/ci/manifest.yml
          path: artifact/demo-app.jar

groups:
  - name: demo-app
    jobs:
      - build
      - deploy-to-dev
      - integration-test
      - deploy-to-prod